### ISSUE TITLE
Description is dependent on leading sequence length

### ISSUE THREAD

**Issue by GuyAllard** [mutalyzer/description-extractor#19]
Example:  
```
>>> s1 = "TAACAATGGAACTTTTTTTTTTTTTTTTTTTTTTTTTTTGCCATTAGA"
>>> s2 = "TAACAATGGATCTTTTTTTTTTTTTTTTTTTTTTTTTGCCATTAGA"
>>> print(describe_dna(s1,s2))
[11_12del;14T>C]
```

Now add 1000 leading nucleotides to each sequence:
```
>>> s1a = 1000 * "A" + s1
>>> s2a = 1000 * "A" + s2
>>> print(describe_dna(s1a,s2a))
1011_1014delinsTC
```
The description has changed from two variants to a single variant.

**Comment by jkvis** [comment]
I think that is the intended behavior. Partly, this is done because of performance issues on very large (whole chromosome) strings. More interesting is the information theoretical aspect; changes are more significant in smaller strings. The `delins` is the *trivial* way to describe a variant. Also note that the resulting description in the second example is indeed smaller: `[1011_1012del;1014T>C]` vs. `1011_1014delinsTC`. Although the reverse is not true: `[11_12del;14T>C]` vs. `11_14delinsTC`.
The splitting and combining of variants can be adjusted using the weighting scheme (requires re-compilation); adding more weight to the trivial description will separate the variants in the second example.
