### ISSUE TITLE
Web version produces different results than Python

### ISSUE THREAD

**Issue by kevin-fang** [mutalyzer/description-extractor#20]
For the web version, when I use the following two sequences:  
Reference: `TTCACTGTTCGGGGCCACTAGCAACAAAGCTTCTGTAAACACTCATGTGCAGGTATTTGTGGACCTGTGTTTTCATTTCCCTTGAGTAAATACCAAGGAATGGAAAAGATGGGTCATATGGTAAGTGTATGTTTAACTTTGTAAGAAACTGCCAAACTGTGTTCCAAAGTGGTGACTGAATTTTCCATTCCCGCCAGGAATGTACGAGAACCACAGTCCTTGCCAACACTTGATGGTCACTCTTTTATC`  
Sample: 
`TTCACTGTTCGGGGCCACTAGCAACAAAGCTTCTGTAAACACTCATGTGCAGGTATTTGTGGACCTGTGTTTTCATTTCCCTTGAGTAAATACCAAGGAATGGAAAAGATGGGTCATATGGTAAGTGTATGTTTAACTTTGTAAGAAACTG------TGT-T-CCAAAGTGGTGACTGAATTTTCCATTCCCGCCAGGAATGTACGAGAACCACAGTCCTTGCCAACACTTGATGGTCACTCTTTTATC`

The following is received as output:
`152_159del`, with a deletion of `CCAAACTG`.

However, when I run the following code in Python:
```python
from extractor import describe_dna
ref = "TTCACTGTTCGGGGCCACTAGCAACAAAGCTTCTGTAAACACTCATGTGCAGGTATTTGTGGACCTGTGTTTTCATTTCCCTTGAGTAAATACCAAGGAATGGAAAAGATGGGTCATATGGTAAGTGTATGTTTAACTTTGTAAGAAACTGCCAAACTGTGTTCCAAAGTGGTGACTGAATTTTCCATTCCCGCCAGGAATGTACGAGAACCACAGTCCTTGCCAACACTTGATGGTCACTCTTTTATC"
sample = "TTCACTGTTCGGGGCCACTAGCAACAAAGCTTCTGTAAACACTCATGTGCAGGTATTTGTGGACCTGTGTTTTCATTTCCCTTGAGTAAATACCAAGGAATGGAAAAGATGGGTCATATGGTAAGTGTATGTTTAACTTTGTAAGAAACTG------TGT-T-CCAAAGTGGTGACTGAATTTTCCATTCCCGCCAGGAATGTACGAGAACCACAGTCCTTGCCAACACTTGATGGTCACTCTTTTATC"
print describe_dna(ref, sample)
```
I get the following results:
`>>> 152_163delins------TGT-T-`

which is different from the web version. The web version and the Python version should return the same results, however.

**Comment by jkvis** [comment]
I don't think that the dash character (`-`) is supported by the description extractor. Possibly these (and other) characters are filtered out by the web server before submitting them to the description extractor. This is supported by the observation that giving the same example as input without the dash characters yields the same answer. Obviously, the filtering does not happens when using the description extractor directly. Here, the dash character is accepted as just another symbol (without any special meaning) resulting in the reported insertion/deletion.

I think that the dash character typically means a "[g]ap of indeterminate length" (IUPAC). As stated before, this is not implemented in the description extractor. Furthermore, one could debate the semantics of consequent dashes in that context. 

The filtering of input in a web environment is necessary to guard the integrity of the server; meaning that it will be difficult to guarantee the same behavior within and outside of a web environment.
